version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'yu-vote-bot:latest'
    volumes:
      - ./data:/usr/src/app/data
      - ./main.py:/usr/src/app/main.py
      - ./src:/usr/src/app/src
